[theme]
primaryColor = "#0E7490"
backgroundColor = "#F7F7F2"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#172B36"
font = "sans-serif"

[server]
maxUploadSize = 2

[client]
showErrorDetails = false
toolbarMode = "minimal"
